_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  asset_injector: 0
  auto_entitylabel: 0
  automated_cron: 0
  az_accordion: 0
  az_block_types: 0
  az_block_types_quick_links: 0
  az_card: 0
  az_carousel: 0
  az_cas: 0
  az_core: 0
  az_event: 0
  az_flexible_block: 0
  az_flexible_page: 0
  az_google_tag: 0
  az_media: 0
  az_metrics: 0
  az_migration: 0
  az_news: 0
  az_paragraphs: 0
  az_paragraphs_accordion: 0
  az_paragraphs_cards: 0
  az_paragraphs_contact: 0
  az_paragraphs_html: 0
  az_paragraphs_photo_gallery: 0
  az_paragraphs_splitscreen: 0
  az_paragraphs_text: 0
  az_paragraphs_text_background: 0
  az_paragraphs_text_media: 0
  az_paragraphs_view: 0
  az_person: 0
  az_security: 0
  az_seo: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  block: 0
  block_class: 0
  block_content: 0
  block_content_permissions: 0
  bootstrap_utilities: 0
  breakpoint: 0
  cas: 0
  chosen: 0
  chosen_lib: 0
  ckeditor5: 0
  ckeditor_bs_grid: 0
  coffee: 0
  conditional_fields: 0
  config: 0
  config_distro: 0
  config_distro_filter: 0
  config_filter: 0
  config_import_single: 0
  config_merge: 0
  config_merge_filter: 0
  config_normalizer: 0
  config_snapshot: 0
  config_sync: 0
  config_update: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  csv_serialization: 0
  ctools: 0
  date_ap_style: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  draggableviews: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_reference_views: 0
  environment_indicator: 0
  exclude_node_title: 0
  feeds: 0
  field: 0
  field_group: 0
  field_group_link: 0
  field_group_migrate: 0
  field_tools: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  form_mode_manager: 0
  google_analytics_counter: 0
  google_tag: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  link: 0
  link_class: 0
  linkit: 0
  media: 0
  media_entity_file_replace: 0
  media_library: 0
  media_library_edit: 0
  media_library_form_element: 0
  media_migration: 0
  media_migration_tools: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migmag: 0
  migmag_process: 0
  migrate: 0
  migrate_devel: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  module_filter: 0
  mysql: 0
  news_migration: 0
  node: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  path: 0
  path_alias: 0
  phpass: 0
  redirect: 0
  responsive_image: 0
  rest: 0
  role_delegation: 0
  s3fs: 0
  search: 0
  search_exclude: 0
  select2: 0
  serialization: 0
  shortcut: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  smart_date: 0
  smart_date_recur: 0
  smart_sql_idmap: 0
  smart_title: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  telephone: 0
  term_merge: 0
  term_reference_change: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_data_export: 0
  views_ui: 0
  viewsreference: 0
  workflows: 0
  xmlsitemap_engines: 0
  extlink: 1
  pathauto: 1
  xmlsitemap: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  config_provider: 100
  az_quickstart: 1000
theme:
  claro: 0
  bootstrap_barrio: 0
  az_barrio: 0
profile: az_quickstart
