_core:
  default_config_hash: Z79EkOuVzTBm1iX5ahkDyRRPnhjQVkyHVFk79ss92Tk
general_settings:
  client_id: ''
  client_secret: ''
  redirect_uri: ''
  cron_interval: 30
  chunk_to_fetch: 1000
  cache_length: 86400
  queue_time: 120
  end_date: '30 days ago +30 days -1 day'
  start_date: '30 days ago'
  custom_start_date: ''
  custom_end_date: ''
  custom_start_day: ''
  custom_end_day: ''
  project_name: ''
  profile_id: ''
  ga4_property_id: '351714646'
  credentials_json_path: /sites/default/files/private/credentials.json
  metric: screenPageViews
  dimension: pagePath
  result_processor: url_alias
  gac_type_az_event: null
  gac_type_az_flexible_page: null
  gac_type_az_news: 1
  gac_type_az_news_story: 1
  gac_type_az_person: null
  gac_type_remove_storage: 0
