_core:
  default_config_hash: fRc8xbZvMt1dVv2chdWSMh8bkLG6uLAYN1Igon0kOn0
first_day: 0
country:
  default: US
timezone:
  default: America/Phoenix
  user:
    configurable: true
    default: 0
    warn: false
